movieprojectlast/movieproject/filterapp/urls.py
# app_name = 'filterapp'
# urlpatterns = [
#
#     path('', views.filter, name='FilterResult'),
#     ]

movieprojectlast/movieproject/movieapp/urls.py
from django.conf.urls.static import static
from django.urls import path

from movieproject import settings
from . import views

app_name = 'movieapp'
urlpatterns = [

    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.details, name='details'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout', views.logout, name='logout'),



]

movieprojectlast/movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
    path('searchapp/',include('searchapp.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieprojectlast/movieproject/searchapp/urls.py
from django.urls import path

from searchapp import views

app_name = 'searchapp'
urlpatterns = [

    path('', views.SearchResult, name='SearchResult'),
    ]

movieprojectlast/movieproject/filterapp/models.py
from django.db import models

# Create your models here.
# import filterapp
# from movieapp.models import Movie
#
#
# class MovieFilter(filterapp.FilterSet):
#     class Meta:
#         model = Movie
#         fields = ['title','category']

movieprojectlast/movieproject/movieapp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Movie(models.Model):
    choices = [
        ("Horror", "Horror"),
        ("Thriller", "Thriller"),
        ("Action", "Action"),
        ("Romance", "Romance"),
        ("Comedy", "Comedy"),
        ("Animated", "Animated"),
    ]
    title = models.CharField(max_length=250)
    description = models.TextField()
    poster = models.ImageField(upload_to="gallery")
    date = models.DateField()
    actors = models.CharField(max_length=200)
    category = models.CharField(max_length=200,choices=choices,null=True)
    # rating = models.IntegerField()
    # trailer_link = models.URLField()
    # added_by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering=('title',)
        verbose_name='Movie'
        verbose_name_plural='Movies'

    def __str__(self):
        return self.title


# class Review(models.Model):
#     user = models.ForeignKey(User,on_delete=models.CASCADE)
#     movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
#     rating = models.IntegerField()
#     comment = models.TextField()
#
#
#     class Meta:
#         ordering=('rating',)
#         verbose_name='Review'
#         verbose_name_plural='Reviews'
#
#     def __str__(self):
#         return self.rating

movieprojectlast/movieproject/searchapp/models.py
from django.db import models

# Create your models here.

movieprojectlast/movieproject/filterapp/forms.py
# from movieapp.models import Movie
#
#
# class MovieFilter(filter.FilterSet):
#     class Meta:
#         model = Movie
#         fields = ['title','category']

movieprojectlast/movieproject/movieapp/forms.py
from django import forms

from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['title','description','poster','date','actors','category']

# class ReviewForm(forms.ModelForm):
#     class Meta:
#         model = Review
#         fields = ['rating','comment']

movieprojectlast/movieproject/filterapp/views.py
# import movie
# from django.shortcuts import render
#
# from filterapp.models import MovieFilter
#
#
# # Create your views here.
# def movie_list(request):
#     filter = MovieFilter(request.GET, queryset=movie.object.all())
#     return render(request, 'filter.html', {'filter':'filter'})

movieprojectlast/movieproject/movieapp/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages, auth

from .filter import MovieFilter
from .forms import MovieForm
from .models import Movie


# Create your views here.
# def index(request):
#     movie = Movie.objects.all()
#     context = {'mlist': movie}
#     return render(request, 'home.html', context)
def index(request):

    movie = MovieFilter(request.GET, queryset=Movie.objects.all()).qs
    print(movie)
    return render(request, 'home.html', {'movies': movie})


def details(request, movie_id):
    result = Movie.objects.get(id=movie_id)
    return render(request, 'details.html', {'movie': result})


def add_movie(request):
    if request.method == "POST":
        form = MovieForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            print('movieadded')
        else:
            print(form.errors)
        return redirect('/')

    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(instance=movie)
    if request.method=='POST':
        form = MovieForm(request.POST,request.FILES,instance=movie)
        if form.is_valid():
            form.save()
            return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['password']
        try:
            if password == confirm_password:
                if User.objects.filter(username=username).exists():
                    messages.info(request, 'username taken')
                    return redirect('movieapp:register')

                else:
                    user = User.objects.create_user(username=username,
                                                    password=password)
                    user.save()
                    print("user registered")
                    messages.info(request, "user registered")
                    return redirect('movieapp:login')

            else:
                messages.info(request, 'password not matching')
                return redirect('movieapp:register')
        except:
            messages.info(request, 'username is mandatory')
            return redirect('movieapp:register')

    return render(request, 'register.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('movieapp:index')
        else:
            messages.info(request, 'invalid')
            return redirect('movieapp:login')

    return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('movieapp:index')


def newpage(request):
    return render(request, 'new.html')


def movie_list(request):
    filter = MovieFilter(request.GET, queryset=Movie.objects.all())
    return render(request, 'filter.html', {'filter': filter})

# def review(request):
#     review = Review.objects.all()
#      context = {'mlist': review}
#      return render(request, 'review.html', context)

movieprojectlast/movieproject/searchapp/views.py
# Create your views here.
from django.db.models import Q
from django.shortcuts import render

from movieapp.models import Movie


def SearchResult(request):
    movies = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        movies = movies.objects.all().filter(Q(title__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'movies': movies})

movieprojectlast/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}

    <input type="text" name="title" placeholder="enter movie title"><br>
    <input type="text" name="description" placeholder="enter movie description"><br>
    <input type="date" name="date"><br>
    <input type="text" name="actors" placeholder="enter movie actors name"><br>
    <input type="file" name="poster"><br>
<!--    <input type="text" name="rating" placeholder="enter movie rating"><br>-->
<!--    <input type="number" min="0" max="10" name="rating" placeholder="enter movie rating"><br>-->
    <div class="wrapper">
        <select name="category " id="category ">
            <option value="">category</option>
            <option value="Horror">Horror</option>
             <option value="Thriller">Thriller</option>
             <option value="Action">Action</option>
             <option value="Romance">Romance</option>
             <option value="Comedy">Comedy</option>
            <option value="Animated">Animated</option>
        </select>
    </div>
<!--    <input type="url" name="trailer_link"><br>-->

    <input type="submit">

<!--    <input type="text" name="comment" placeholder="enter movie comment"><br>-->
<!--<input type="text" name="rating" placeholder="enter movie rating"><br>-->





</form>
{% endblock %}

movieprojectlast/movieproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<nav class="navbar navbar-dark bg-dark">
<a class="navbar-brand" href="#">
    <h2>ONLINE MOVIE STORE</h2><br>


<!--    <form class="d-flex" action="" method="get">-->

<!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="search" aria-label="Search">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i>Search</button>-->
<!--    </form>-->




<!--                {% if user.is_authenticated %}-->
<!--                <li >hello  {{ user.username }}</li>-->

<!--                  <a class="btn btn-primary" href="{% url 'movieapp:logout' %}"> Logout </a>-->
<!--                  <a class="btn btn-primary" href="{% url 'movieapp:add_movie' %}"> Add movie </a><br>-->
<!--                {% else %}-->
<!--                  <a class="btn btn-primary" href="{% url 'movieapp:login' %}"> Login </a><br>-->
<!--                  <a class="btn btn-primary" href="{% url 'movieapp:register' %}"> Register </a>-->
<!--                {% endif %}-->


</nav>




{% block body %}
{% endblock %}
</body>
</html>
<body style="https://wallpapercave.com/wp/wp1945898.jpg')">

movieprojectlast/movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    are you sure?

    <button type="submit" class="btb btn-danger">delete</button>

</form>
{% endblock %}

movieprojectlast/movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md 6">
            <img src="{{movie.poster.url}}" width="300" height="400"><br>
        </div>

<div class="col-md 6">
    {{ movie.title }}<br>
    {{ movie.description }}<br>
    {{ movie.date }}<br>
    {{ movie.actors }}<br>
    {{ movie.category }}<br>



    <a class='btb btn-warning' href="{% url 'movieapp:update' movie.id %}">update</a><br>
    <a class='btb btn-danger' href="{% url 'movieapp:delete' movie.id %}">delete</a><br>
<!--    {{ movie.rating }}<br>-->
<!--    {{ movie.comment }}<br>-->
<!--    <div class="container">-->
<!--    <div class="row">-->
<!--&lt;!&ndash;        <div class="col-md 6">&ndash;&gt;     <link rel="{{movie.trailer_link.url}}"><br>-->
<!--        </div>-->




<!--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->

<!--<span class="fa fa-star checked"></span>-->
<!--<span class="fa fa-star checked"></span>-->
<!--<span class="fa fa-star checked"></span>-->
<!--<span class="fa fa-star"></span>-->
<!--<span class="fa fa-star"></span>-->





<!--<form action="/action_page.php">-->
<!--&lt;!&ndash;  <p><label for="w3review">Review of W3Schools:</label></p>&ndash;&gt;-->
<!--  <textarea id="w3review" name="w3review" rows="4" cols="50"></textarea>-->
<!--  <br>-->
<!--&lt;!&ndash;  <input type="submit">&ndash;&gt;-->
<!--</form>-->








{% endblock %}
    </div>
         </div>
</div>
        </div>
</div>

movieprojectlast/movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit">

</form>

movieprojectlast/movieproject/templates/filter.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">

        {% for i in mlist %}
        <div class="mt-5">
        <div class="col-md-3">
            <div class="card" style="width:15rem;">
  <img class="card-img-top" src="{{i.poster.url}}" alt="..." width="100px" height="250px">
  <div class="card-body">
    <h3 class="card-title">{{i.title}}</h3>
    <p class="card-text">{{i.description}}</p>
      <p class="card-text">{{i.date}}</p>
      <p class="card-text">{{i.actors}}</p>
      <p class="card-text">{{i.category}}</p>
<!--      <p class="card-text">{{i.comment}}</p>-->
<!--      <p class="card-text">{{i.rating}}</p>-->
<!--      <link class="card-link-top" rel="{{i.trailer_link.url}}">-->
      <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">view details</a>
  </div>
</div>
            </div>
        </div>
        {% endfor %}
    </div>



{% endblock %}
</div>

movieprojectlast/movieproject/templates/index.html
<!--{% extends 'base.html' %}-->
{% block body %}

<div class="container">
    <div class="row">

        {% for i in mlist %}
        <div class="mt-5">
        <div class="col-md-3">
            <div class="card" style="width:15rem;">
  <img class="card-img-top" src="{{i.poster.url}}" alt="..." width="100px" height="250px">
  <div class="card-body">
    <h3 class="card-title">{{i.title}}</h3>
    <p class="card-text">{{i.description}}</p>
      <p class="card-text">{{i.date}}</p>
      <p class="card-text">{{i.actors}}</p>
      <p class="card-text">{{i.category}}</p>
<!--      <p class="card-text">{{i.rating}}</p>-->
      <!--      <p class="card-text">{{i.comment}}</p>-->
<!--      <link class="card-link-top" rel="{{i.trailer_link.url}}">-->
      <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">view details</a>
  </div>
</div>
            </div>
        </div>
        {% endfor %}
    </div>



{% endblock %}
</div>

movieprojectlast/movieproject/templates/login.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Glassmorphism login Form Tutorial in html css</title>


</head>
<body>
<!-- partial:index.partial.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Glassmorphism login Form Tutorial in html css</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form action='' method="post">
    {% csrf_token %}
        <h3>Login Here</h3>

        <label>Username</label>
        <input type="text" placeholder="Username" name="username">

        <label>Password</label>
        <input type="password" placeholder="Password" name="password">
<!--         <div class="row">-->
<!--            	<div class="remember">-->
<!--					<div>-->
<!--        <input type="checkbox" name="remember" value="Remember me"><span>Remember me</span>-->
<!--					</div>-->
<!--        <a href="#">Forget password ?</a>-->
<!--            	</div>-->
<!--            </div>-->
<div>

    <button type="submit" >SUBMIT</button>
       <br>
        <a href="{% url 'movieapp:register' %}">Register Here</a><br>
    </div>
{% for msg in messages %}
<h4>{{ msg }}</h4>
{% endfor %}
    </form>
</body>
</html>

</body></html>

movieprojectlast/movieproject/templates/new.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Glassmorphism login Form Tutorial in html css</title>


</head>
<body>
<!-- partial:index.partial.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Glassmorphism login Form Tutorial in html css</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form action='form' >

        <h3>Click Here To Continue</h3>


<div>

    <button type="submit" >FILL FORM TO GET COMPLETED</button>
       <br>

    </div>
        <br>
        <br>
        <br>
        <div class="social">
          <div class="go"><i class="fab fa-google"></i>  Google</div>
          <div class="fb"><i class="fab fa-facebook"></i>  Facebook</div>
        </div>
    </form>
</body>
</html>

</body></html>

movieprojectlast/movieproject/templates/register.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Glassmorphism login Form Tutorial in html css</title>


</head>
<body>
<!-- partial:index.partial.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Glassmorphism login Form Tutorial in html css</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 25px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
   <form action='' method="post">
    {% csrf_token %}
        <h3>Register Here</h3>

        <label>Username</label>
        <input type="text" placeholder="Enter your username" name="username">

        <label>Password</label>
        <input type="password" placeholder="Enter your password" name="password">

        <label>Confirm Password</label>
        <input type="password" placeholder="Confirm password" name="password1">
<div>
     <button type="submit">SUBMIT</button></a>
       <br>
{% for msg in messages %}
<h4>{{ msg }}</h4>
{% endfor %}
    </div>

    </form>
</body>
</html>

</body></html>

movieprojectlast/movieproject/templates/search.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}
   we have variety of movies .
{% endblock %}


{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">you have searched for:<b>"{{query}}"</b></p>
</div>
<div class="container" >
    <div class="row mx_auto">
        {% for movie in movies %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="mt-5">
                <div class="card text-center" style="min-width:18rem;">
                    <a href="{{title.get_url}}"><img class="card-img-top my_image" src="{{title.image.url}}" alt="{{title.name}}" width="200px" height="200px"></a>
                    <div class="card-body">
                        <h4>{{movie.title}}</h4>
                        <p>{{movie.category}}</p>
                    </div>
                    {% empty %}
                    <div class="row mx-auto">
                        <p class="text-center my_search_text"> 0 results found</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}